# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

os: osx
language: swift
osx_image: xcode10.2

stages:
  - name: pretest
  - name: test
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: pretest
      name: Check Linux tests are sync’d
      install: swift test --generate-linuxmain
      script: git diff --exit-code

    - name: macOS / Swift 4.2.1 (Xcode 10.1)
      osx_image: xcode10.1
      stage: test
      script: swift test

    - name: macOS / Swift 5.0.0 (Xcode 10.2)
      script: swift test

    - &linux
      name: Linux / Swift 4.2.3
      env: SWIFT_VERSION=4.2.3
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      os: linux
      osx_image: null
      language: generic
      script: swift test
      
    - <<: *linux
      name: Linux / Swift 5.0.1
      env: SWIFT_VERSION=5.0.1

    - stage: deploy
      script: |
        set -exo pipefail

        git clone "https://$GITHUB_TOKEN@github.com/mxcl/homebrew-made.git"
        cd homebrew-made

        MIDDLE=$TRAVIS_VERSION.mojave.bottle
        SUFFIX=$MIDDLE.tar.gz
        brew install --build-bottle ./swift-sh.rb
        brew bottle --json --root-url=https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_VERSION ./swift-sh.rb
        brew bottle --json swift-sh--$MIDDLE.json --merge --write --no-commit ./swift-sh.rb

        SHA256=$(brew --cache --build-from-source swift-sh | xargs cat | shasum --algorithm 256 --binary | awk '{print $1}')
        sed -E -i 's/^  sha256 ".+"/^  sha256 "'$SHA256\"/ ./swift-sh.rb
        sed -E -i '^  s~url ".+"~^  url "'$URL\"~ ./swift-sh.rb

        curl -O https://raw.githubusercontent.com/mxcl/ops/master/deploy
        chmod u+x deploy
        RELEASE_ID=$(./deploy publish-release)

        curl --data-binary @"swift-sh--$SUFFIX" \
          "https://uploads.github.com/repos/$TRAVIS_REPO_SLUG/releases/$RELEASE_ID/assets?name=swift-sh-$SUFFIX" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/octet-stream"

        git add swift-sh.rb
        git config user.name "Travis"
        git config user.email "bot@travis-ci.com"
        git commit -m "swift-sh $TRAVIS_TAG"
        git push origin master
