# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

language: generic

stages:
  - name: pretest
  - name: test
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: pretest
      name: Check Linux tests are sync’d
      install: swift test --generate-linuxmain
      script: git diff --exit-code
      os: osx
      osx_image: xcode10.2

    - name: macOS / Swift 4.2.1 (Xcode 10.1)
      stage: test
      os: osx
      language: swift
      osx_image: xcode10.1
      script: swift test

    - name: macOS / Swift 5.0.0-beta (Xcode 10.2)
      os: osx
      language: swift
      osx_image: xcode10.2
      script: swift test

    - &linux
      name: Linux / Swift 4.2.2
      env: SWIFT_VERSION=4.2.2
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
      
    - <<: *linux
      name: Linux / Swift 5.0.0-dev+2019.02.03
      env: SWIFT_VERSION=DEVELOPMENT-SNAPSHOT-2019-02-03-a

    - name: Bump Formula
      stage: deploy
      script: |
        set -exo pipefail
        URL="https://github.com/mxcl/swift-sh/archive/$TRAVIS_TAG.tar.gz"
        SHA256=$(curl --location "$URL" | shasum --algorithm 256 --binary | awk '{print $1}')
        git clone "https://$GITHUB_TOKEN@github.com/mxcl/homebrew-made.git"
        cd homebrew-made
        sed -E -i 's/sha256 ".+"/sha256 "'$SHA256\"/ swift-sh.rb
        sed -E -i 's~url ".+"~url "'$URL\"~ swift-sh.rb
        git add swift-sh.rb
        git config user.name "Travis"
        git config user.email "bot@travis-ci.com"
        git commit -m "swift-sh $TRAVIS_TAG"
        git push origin master

    - name: Publish Release
      script: swift run swift-sh <(curl https://raw.githubusercontent.com/mxcl/Path.swift/master/.github/deploy) publish-release
      os: osx
      osx_image: xcode10.2
