
# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - os: osx
      language: swift
      osx_image: xcode10.1
      script: swift test
    - env: SWIFT_VERSION=4.2.1
      os: linux
      language: generic
      dist: trusty
      sudo: false
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test
