# only run for: merge commits, releases and pull-requests
if: branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

os: osx

stages:
  - name: deploy
    if: branch =~ ^\d+\.\d+\.\d+$

jobs:
  include:
    - stage: deploy
      osx_image: xcode11
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - HOMEBREW_NO_INSTALL_CLEANUP=1
      script: |
        brew tap mxcl/homebrew-made
        cd /usr/local/Homebrew/Library/Taps/mxcl/homebrew-made
        
        # update our formula to new tag
        URL="https://github.com/mxcl/swift-sh/archive/$TRAVIS_TAG.tar.gz"
        sed -E -i '' 's~^  url ".+"~  url "'$URL\"~ ./swift-sh.rb
        brew fetch swift-sh || true
        # ^^ fails because SHA is wrong, hence || true
        
        SHA256=$(shasum --algorithm 256 $(brew --cache --build-from-source swift-sh) | awk '{print $1}')
        sed -E -i '' 's/^  sha256 ".+"/  sha256 "'$SHA256\"/ ./swift-sh.rb
        
        # update bottle
        MIDDLE=$TRAVIS_TAG.mojave.bottle
        SUFFIX=$MIDDLE.tar.gz
        brew install --build-bottle ./swift-sh.rb
        brew bottle --json --root-url=https://github.com/$TRAVIS_REPO_SLUG/releases/download/$TRAVIS_TAG ./swift-sh.rb
        brew bottle --merge swift-sh--$MIDDLE.json --write --no-commit

        git remote set-url origin "https://$GITHUB_TOKEN@github.com/mxcl/homebrew-made.git"
        git add swift-sh.rb
        git config user.name "Travis"
        git config user.email "bot@travis-ci.com"
        git commit -m "swift-sh $TRAVIS_TAG"
        git push origin master
        
        curl -O https://raw.githubusercontent.com/mxcl/ops/master/deploy
        chmod u+x deploy
        RELEASE_ID=$(./deploy publish-release)
        
        # upload bottle
        curl --data-binary @"swift-sh--$SUFFIX" \
          "https://uploads.github.com/repos/$TRAVIS_REPO_SLUG/releases/$RELEASE_ID/assets?name=swift-sh-$SUFFIX" \
          -H "Authorization: token $GITHUB_TOKEN" \
          -H "Content-Type: application/octet-stream"

      after_script: sleep 1
