# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - name: macOS / Swift 4.2.1 (Xcode 10.1)
      os: osx
      language: swift
      osx_image: xcode10.1
      script: swift test

    - name: Linux / Swift 4.2.1
      env: SWIFT_VERSION=4.2.1
      os: linux
      language: generic
      dist: trusty
      sudo: false
      install: eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
      script: swift test

    - stage: deploy
      if: branch =~ ^\d+\.\d+\.\d+$
      script: |
        URL="https://github.com/mxcl/swift-sh/archive/$TRAVIS_TAG.tar.gz"
        curl --location --output out "$URL"
        SHA256=$(shasum --binary --algorithm 256 out | awk '{print $1}')
        git clone "https://$GITHUB_TOKEN@github.com/mxcl/homebrew-made.git"
        cd homebrew-made
        sed --in-place "s/sha256 \"([\w]+)\"/sha256 \"$SHA256\"/" swift-sh.rb
        sed --in-place "s/url \"([\w]+)\"/url \"$URL\"/" swift-sh.rb
        git add swift-sh.rb
        git config user.name  "Travis"
        git config user.email "bot@travis-ci.com"
        git commit -m "swift-sh $TRAVIS_TAG"
        git push origin master
